name: VersionCheck (master)

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  VersionCheck_feature:

    name: VersionCheck (master)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetching
      run: git fetch --prune --unshallow origin +refs/heads/*:refs/remotes/origin/*
    - name: Running the script to check the version
      run: bash .github/scripts/VersionCheck\ \(master\).sh